spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

# Configuración de la base de datos MySQL en AWS RDS
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.platform=mysql

# Esto asegura que los datos se carguen al iniciar
spring.sql.init.mode=always
# Asegura que Hibernate cree las tablas si no existen antes de insertar los datos
spring.jpa.hibernate.ddl-auto=update

# Configuraci�n de Hibernate
spring.jpa.database=mysql
#spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html